import { ServiceOrder } from '../../features/service-orders/models/service-order.model';

export const SERVICE_ORDERS_MOCK: ServiceOrder[] = [
  {
    id: 1,
    os: '2025-001',
    servico: 'Instalação de ponto comercial',
    tipo: 'Comercial',
    prioridade: 'MEDIA',
    status: 'ABERTO',
    valor: 4500,
    prazoDias: 5,
    bairro: 'Planalto',
    latitude: -3.0675,
    longitude: -60.0421,
    endereco: 'Av. Brasil, 1234',
  },
  
  {
    id: 2,
    os: '2025-002',
    servico: 'Manutenção de Poste',
    tipo: 'Manutenção',
    prioridade: 'MEDIA',
    status: 'EM_EXECUCAO',
    valor: 1200,
    prazoDias: 2,
    bairro: 'Alvorada',
    latitude: -3.0803,
    longitude: -60.0605,
    endereco: 'Rua das Flores, 567',
  },

  {
    id: 3,
    os: '2025-003',
    servico: 'Poda de Árvores',
    tipo: 'Obras',
    prioridade: 'URGENTE',
    status: 'ATRIBUIDO',
    valor: 9800,
    prazoDias: 10,
    bairro: 'Planalto',
    latitude: -3.0668,
    longitude: -60.0430,
    endereco: 'Av. Central, 890',
  },

  {
    id: 4,
    os: '2025-004',
    servico: 'Religação Normal',
    tipo: 'Comercial',
    prioridade: 'ALTA',
    status: 'CONCLUIDO',
    valor: 4500,
    prazoDias: 7,
    bairro: 'Centro',
    latitude: -3.0799,
    longitude: -60.0598,
    endereco: 'Avenida Principal, 500',
  },

  {
    id: 5,
    os: '2025-004',
    servico: 'Religação de Urgência',
    tipo: 'Comercial',
    prioridade: 'ALTA',
    status: 'ABERTO',
    valor: 4500,
    prazoDias: 7,
    bairro: 'Alvorada',
    latitude: -3.0799,
    longitude: -60.0598,
    endereco: 'Rua do Sol, 234',
  },

  {
  id: 6,
  os: '2025-005',
  servico: 'Instalação de Medidor',
  tipo: 'Comercial',
  prioridade: 'MEDIA',
  status: 'ABERTO',
  valor: 2800,
  prazoDias: 10,
  bairro: 'Cidade Nova',
  latitude: -3.0219,
  longitude: -59.9785,
  endereco: 'Av. Nova, 345',
},

{
  id: 7,
  os: '2025-006',
  servico: 'Manutenção de Rede Elétrica',
  tipo: 'Manutenção',
  prioridade: 'BAIXA',
  status: 'ABERTO',
  valor: 1500,
  prazoDias: 15,
  bairro: 'Parque Dez',
  latitude: -3.1033,
  longitude: -60.0256,
  endereco: 'Rua das Acácias, 678',
},
];
